GET http://localhost:5200/games

###
GET http://localhost:5200/games/3

###
POST  http://localhost:5200/games
Content-Type: application/json

{
    "name": "Grand Theft Auto 5",
    "genreId": 4,
    "price": 80.00,
    "releaseDate": "2014-08-20"
}

###
PUT http://localhost:5200/games/3
Content-Type: application/json

{
    "name": "Grand Theft Auto 5",
    "genreId": 4,
    "price": 78.00,
    "releaseDate": "2014-08-20"
}

###
DELETE http://localhost:5200/games/4